// Code generated by MockGen. DO NOT EDIT.
// Source: player.go

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	discordgo "github.com/bwmarrin/discordgo"
	gomock "github.com/golang/mock/gomock"
)

// MockUserFetcher is a mock of UserFetcher interface.
type MockUserFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockUserFetcherMockRecorder
}

// MockUserFetcherMockRecorder is the mock recorder for MockUserFetcher.
type MockUserFetcherMockRecorder struct {
	mock *MockUserFetcher
}

// NewMockUserFetcher creates a new mock instance.
func NewMockUserFetcher(ctrl *gomock.Controller) *MockUserFetcher {
	mock := &MockUserFetcher{ctrl: ctrl}
	mock.recorder = &MockUserFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFetcher) EXPECT() *MockUserFetcherMockRecorder {
	return m.recorder
}

// User mocks base method.
func (m *MockUserFetcher) User(userID string, options ...discordgo.RequestOption) (*discordgo.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{userID}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "User", varargs...)
	ret0, _ := ret[0].(*discordgo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// User indicates an expected call of User.
func (mr *MockUserFetcherMockRecorder) User(userID interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{userID}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockUserFetcher)(nil).User), varargs...)
}

// MockUserCacheApi is a mock of UserCacheApi interface.
type MockUserCacheApi struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheApiMockRecorder
}

// MockUserCacheApiMockRecorder is the mock recorder for MockUserCacheApi.
type MockUserCacheApiMockRecorder struct {
	mock *MockUserCacheApi
}

// NewMockUserCacheApi creates a new mock instance.
func NewMockUserCacheApi(ctrl *gomock.Controller) *MockUserCacheApi {
	mock := &MockUserCacheApi{ctrl: ctrl}
	mock.recorder = &MockUserCacheApiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCacheApi) EXPECT() *MockUserCacheApiMockRecorder {
	return m.recorder
}

// GetPlayer mocks base method.
func (m *MockUserCacheApi) GetPlayer(ctx context.Context, playerID string) (Player, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlayer", ctx, playerID)
	ret0, _ := ret[0].(Player)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlayer indicates an expected call of GetPlayer.
func (mr *MockUserCacheApiMockRecorder) GetPlayer(ctx, playerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlayer", reflect.TypeOf((*MockUserCacheApi)(nil).GetPlayer), ctx, playerID)
}

// GetUsername mocks base method.
func (m *MockUserCacheApi) GetUsername(ctx context.Context, playerID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsername", ctx, playerID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsername indicates an expected call of GetUsername.
func (mr *MockUserCacheApiMockRecorder) GetUsername(ctx, playerID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsername", reflect.TypeOf((*MockUserCacheApi)(nil).GetUsername), ctx, playerID)
}
